/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/chair.glb -t
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { MeshStandardMaterial } from "three";
import useMaterial from "../hooks/useMaterial";
import useStore from "../hooks/useStore";
import { MATERIALS } from "../constants";

type GLTFResult = GLTF & {
  nodes: {
    Traverso_Basso_HP: THREE.Mesh;
    Rete001_Seduta: THREE.Mesh;
    Rete001_Schienale: THREE.Mesh;
    Cordino_02: THREE.Mesh;
    Gamba_HP: THREE.Mesh;
    Cordino: THREE.Mesh;
    Traverso_Alto_HP: THREE.Mesh;
    Traverso_laterale_1_HP: THREE.Mesh;
    Traverso_posteriore_1_HP: THREE.Mesh;
    Traverso_frontale_1_HP: THREE.Mesh;
    Traverso_posteriore_2_HP: THREE.Mesh;
    Traverso_laterale_2_HP: THREE.Mesh;
    Traverso_frontale_2_HP: THREE.Mesh;
  };
};

const defaultMaterial = new MeshStandardMaterial({ color: "beige" });

export function Chair(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("models/chair.glb") as GLTFResult;
  const { selectedMaterial } = useStore();
  const woodMaterial = useMaterial(MATERIALS[selectedMaterial]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Traverso_Basso_HP.geometry}
        material={woodMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rete001_Seduta.geometry}
        material={defaultMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Rete001_Schienale.geometry}
        material={defaultMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cordino_02.geometry}
        material={defaultMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Gamba_HP.geometry}
        material={woodMaterial}
        position={[-0.29, 0.38, -0.28]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Cordino.geometry}
        material={defaultMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Traverso_Alto_HP.geometry}
        material={woodMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Traverso_laterale_1_HP.geometry}
        material={woodMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Traverso_posteriore_1_HP.geometry}
        material={woodMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Traverso_frontale_1_HP.geometry}
        material={woodMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Traverso_posteriore_2_HP.geometry}
        material={woodMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Traverso_laterale_2_HP.geometry}
        material={woodMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Traverso_frontale_2_HP.geometry}
        material={woodMaterial}
        position={[0.33, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/models/chair.glb");
